-- Insert 20 Demo Products (5 per category)
INSERT INTO products (name, slug, description, short_description, base_price, category_id, image_url, bestseller, active)
VALUES
  -- Birthday Cakes
  ('Classic Chocolate Truffle', 'classic-chocolate-truffle', 'A rich, decadent chocolate truffle cake, perfect for birthday celebrations.', 'Rich chocolate truffle', 550, (SELECT id FROM categories WHERE slug='birthday-cakes'), 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&q=80', true, true),
  ('Rainbow Confetti Cake', 'rainbow-confetti-cake', 'Colorful layers of vanilla sponge with funfetti sprinkles inside and out.', 'Fun vanilla confetti cake', 600, (SELECT id FROM categories WHERE slug='birthday-cakes'), 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=500&q=80', false, true),
  ('Strawberry Shortcake', 'strawberry-shortcake', 'Fresh strawberries layered with light vanilla cream and soft sponge.', 'Fresh strawberry cream', 650, (SELECT id FROM categories WHERE slug='birthday-cakes'), 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=500&q=80', true, true),
  ('Black Forest Delight', 'black-forest-delight', 'Traditional black forest with cherry compote and chocolate shavings.', 'Classic cherry chocolate', 500, (SELECT id FROM categories WHERE slug='birthday-cakes'), 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=500&q=80', false, true),
  ('Butterscotch Crunch', 'butterscotch-crunch', 'Caramelized nuts and smooth butterscotch frosting over a soft sponge.', 'Caramel nut crunch', 550, (SELECT id FROM categories WHERE slug='birthday-cakes'), 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=500&q=80', false, true),

  -- Anniversary Cakes
  ('Red Velvet Romance', 'red-velvet-romance', 'Luxurious red velvet sponge with smooth cream cheese frosting.', 'Premium cream cheese', 700, (SELECT id FROM categories WHERE slug='anniversary-cakes'), 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=500&q=80', true, true),
  ('Heart Shaped Pineapple', 'heart-shaped-pineapple', 'Fresh pineapple chunks in a romantic heart-shaped vanilla cake.', 'Fresh pineapple flavor', 650, (SELECT id FROM categories WHERE slug='anniversary-cakes'), 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&q=80', false, true),
  ('Rose Gold Floral Cake', 'rose-gold-floral', 'Elegant vanilla cake adorned with edible rose gold and buttercream flowers.', 'Elegant floral design', 850, (SELECT id FROM categories WHERE slug='anniversary-cakes'), 'https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=500&q=80', true, true),
  ('Choco-Berry Tier', 'choco-berry-tier', 'Two-tier chocolate cake covered in fresh seasonal berries.', 'Chocolate & fresh berries', 1200, (SELECT id FROM categories WHERE slug='anniversary-cakes'), 'https://images.unsplash.com/photo-1562214695-1f9e9cf2d5b6?w=500&q=80', false, true),
  ('Champagne Infused Cake', 'champagne-infused', 'Sophisticated champagne infused cream with delicate vanilla layers.', 'Sophisticated champagne flavor', 950, (SELECT id FROM categories WHERE slug='anniversary-cakes'), 'https://images.unsplash.com/photo-1623356064972-e1d55f5fbe1a?w=500&q=80', false, true),

  -- Wedding Cakes
  ('Three-Tier Vanilla Elegance', 'three-tier-vanilla', 'A grand three-tier vanilla bean cake for your special day.', 'Grand three-tier design', 3500, (SELECT id FROM categories WHERE slug='wedding-cakes'), 'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?w=500&q=80', true, true),
  ('Rustic Semi-Naked Cake', 'rustic-semi-naked', 'Trendy semi-naked frosting dressed with real floral arrangements.', 'Trendy rustic aesthetic', 2800, (SELECT id FROM categories WHERE slug='wedding-cakes'), 'https://images.unsplash.com/photo-1550981977-96a94f6e246f?w=500&q=80', true, true),
  ('White Fondant Pearl', 'white-fondant-pearl', 'Flawless white fondant adorned with edible pearls and lace.', 'Flawless fondant finish', 4000, (SELECT id FROM categories WHERE slug='wedding-cakes'), 'https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=500&q=80', false, true),
  ('Gold Leaf Chocolate Tier', 'gold-leaf-chocolate', 'Rich chocolate layers wrapped in edible 24k gold leaf.', 'Luxurious gold leaf', 4500, (SELECT id FROM categories WHERE slug='wedding-cakes'), 'https://images.unsplash.com/photo-1622896784083-cc051313dbab?w=500&q=80', false, true),
  ('Lemon Raspberry Wedding', 'lemon-raspberry-wedding', 'Refreshing lemon sponge layered with tart raspberry compote.', 'Refreshing lemon raspberry', 3200, (SELECT id FROM categories WHERE slug='wedding-cakes'), 'https://images.unsplash.com/photo-1605807646983-377bc5a76493?w=500&q=80', false, true),

  -- Bento Cakes
  ('Mini Chocolate Bento', 'mini-chocolate-bento', 'A cute 300g chocolate cake perfect for a small celebration.', 'Cute 300g chocolate cake', 350, (SELECT id FROM categories WHERE slug='bento-cakes'), 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=500&q=80', true, true),
  ('Pastel Dream Bento', 'pastel-dream-bento', 'Light vanilla bento cake decorated with beautiful pastel frosting.', 'Beautiful pastel frosting', 350, (SELECT id FROM categories WHERE slug='bento-cakes'), 'https://images.unsplash.com/photo-1614145121029-83a9f7b68bf4?w=500&q=80', true, true),
  ('Minimalist Message Bento', 'minimalist-message-bento', 'Simple white aesthetic with your custom short message on top.', 'Custom short message', 350, (SELECT id FROM categories WHERE slug='bento-cakes'), 'https://images.unsplash.com/photo-1605333550266-9b63a6dc50bc?w=500&q=80', false, true),
  ('Coffee Mocha Bento', 'coffee-mocha-bento', 'Intense coffee and chocolate flavors in a cute mini box.', 'Intense coffee chocolate', 380, (SELECT id FROM categories WHERE slug='bento-cakes'), 'https://images.unsplash.com/photo-1571115177098-24edf4c4a45a?w=500&q=80', false, true),
  ('Matcha Green Tea Bento', 'matcha-green-tea-bento', 'Premium matcha flavor for tea lovers in a bento size.', 'Premium matcha flavor', 400, (SELECT id FROM categories WHERE slug='bento-cakes'), 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?w=500&q=80', false, true);
